# Generated by Django 3.0.8 on 2020-08-23 21:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200823_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 21, 9, 38, 443427, tzinfo=utc)),
        ),
    ]
