# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestAsdf():
    def setup_method(self, method):
        self.driver = webdriver.Firefox(executable_path=r"C:\driver_selenium\geckodriver.exe")
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_asdf(self):
        self.driver.get("https://elecciones2020.do/Verificate")
        self.driver.set_window_size(998, 1050)
        self.driver.find_element(By.ID , "mun_ced").click()
        self.driver.find_element(By.ID, "mun_ced").send_keys("402")
        self.driver.find_element(By.ID, "seq_ced").send_keys("2415105")
        self.driver.find_element(By.ID, "ver_ced").send_keys("6")
        self.driver.find_element(By.NAME, "Terms").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
        time.sleep(5)
        self.driver.close()

