
# Generated by Selenium IDE
import pytest
import time
import json
import unittest
import time
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestAdfg(unittest.TestCase):
    def setUp(self):
        chrome_options = Options()
        chrome_options.add_argument("--headless")
        #self.driver = webdriver.Chrome(options=chrome_options, executable_path=r"C:\driver_selenium\chromedriver.exe")
        self.driver = webdriver.Chrome(executable_path=r"C:\driver_selenium\chromedriver.exe")


    def test_bhd(self):
        driver = self.driver
        driver.get("https://www.bhdleon.com.do")
        driver.switch_to.frame(0)
        driver.switch_to.default_content()
        driver.find_element(By.XPATH, "//*[@id='footer']/section[2]/div/ul/li[5]/a").click()

        bhd_dolar_buy = driver.find_element(By.XPATH, '//*[@id="TasasDeCambio"]/table/tbody/tr[2]/td[2]').text
        bhd_dolar_sell = driver.find_element(By.XPATH, '//*[@id="TasasDeCambio"]/table/tbody/tr[2]/td[3]').text
        bhd_euro_buy = driver.find_element(By.XPATH, '//*[@id="TasasDeCambio"]/table/tbody/tr[3]/td[2]').text
        bhd_euro_sell = driver.find_element(By.XPATH, '//*[@id="TasasDeCambio"]/table/tbody/tr[3]/td[3]').text
        print(f"bhd_dolar_buy: {bhd_dolar_buy}")
        print(f"bhd_dolar_sell: {bhd_dolar_sell}")
        print(f"bhd_euro_buy: {bhd_euro_buy}")
        print(f"bhd_euro_sell: {bhd_euro_sell}")
        driver.close()

    def test_bankreservas(self):
        driver = self.driver
        driver.get("https://www.banreservas.com/")
        driver.find_element_by_xpath('/html/body/header/div[1]/div/div[1]/div[1]/ul/li/a/b').click()
        bankreservas_dolar_buy = driver.find_element_by_xpath('/html/body/header/div[1]/div/div[1]/div[1]/ul/li/div/table/tbody/tr[2]/td[2]').text
        bankreservas_dolar_sell = driver.find_element_by_xpath('/html/body/header/div[1]/div/div[1]/div[1]/ul/li/div/table/tbody/tr[2]/td[3]').text
        bankreservas_euro_buy = driver.find_element_by_xpath('/html/body/header/div[1]/div/div[1]/div[1]/ul/li/div/table/tbody/tr[3]/td[2]').text
        bankreservas_euro_sell = driver.find_element_by_xpath('/html/body/header/div[1]/div/div[1]/div[1]/ul/li/div/table/tbody/tr[3]/td[3]').text
        print(f"bankreservas_dolar_buy: {bankreservas_dolar_buy}")
        print(f"bankreservas_dolar_sell: {bankreservas_dolar_sell}")
        print(f"bankreservas_euro_buy: {bankreservas_euro_buy}")
        print(f"bankreservas_euro_sell: {bankreservas_euro_sell}")
        driver.close()


    def test_asocpopular(self):
        driver = self.driver
        driver.get("https://www.apap.com.do/")
        driver.set_window_size(1296, 738)

        asoc_popular_dolar_sell = driver.find_element(By.ID, "currency-sell").text
        asoc_popular_dolar_buy = driver.find_element(By.ID, "currency-buy").text
        driver.find_element(By.ID, "currency-label").click()
        driver.find_element(By.LINK_TEXT, "EUR").click()
        asoc_popular_euro_sell = driver.find_element(By.ID, "currency-sell").text
        asoc_popular_euro_buy = driver.find_element(By.ID, "currency-buy").text

        print(f"asoc_popular_dolar_buy: {asoc_popular_dolar_buy}")
        print(f"asoc_popular_dolar_sell: {asoc_popular_dolar_sell}")
        print(f"asoc_popular_euro_buy: {asoc_popular_euro_buy}")
        print(f"asoc_popular_euro_sell: {asoc_popular_euro_sell}")
        driver.close()


    # def test_testpopularbank(self):
    #     driver = self.driver
    #     driver.get("https://www.popularenlinea.com/personas/Paginas/Home.aspx")
    #     driver.set_window_size(1296, 738)
    #
    #     driver.find_element(By.CLASS_NAME, "BPD-icon2-pro-35").click()
    #     popular_bank_dolar_buy = driver.find_element(By.ID, "compra_peso_dolar_desktop").text
    #     popular_bank_dolar_sell = driver.find_element(By.ID, "venta_peso_dolar_desktop").text
    #     driver.find_element(By.CSS_SELECTOR, ".btn_tasa_euro").click()
    #     popular_bank_euro_buy = driver.find_element(By.ID, "compra_peso_euro_desktop").text
    #     popular_bank_euro_sell = driver.find_element(By.ID, "venta_peso_euro_desktop").text
    #
    #     print(f"popular_bank_dolar_buy: {popular_bank_dolar_buy}")
    #     print(f"popular_bank_dolar_sell: {popular_bank_dolar_sell}")
    #     print(f"popular_bank_euro_buy: {popular_bank_euro_buy}")
    #     print(f"popular_bank_euro_sell: {popular_bank_euro_sell}")
    #
    #     driver.close()



    def tearDown(self):
        self.driver.quit()

if __name__ == '__main__':
    unittest.main()


